In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
def multimax(x):
  t = x[np.nonzero(x)]
  return np.all(t==t[0])

In [ ]:
def act(x):
  if x >= 0:
    return x
  else:
    return 0

In [ ]:
def sum_j(x,i):
  return sum(x)-x[i]

In [ ]:
def maxnet(x, e):
  print(x)
  xt = x.copy()
  while not multimax(xt) and len(np.nonzero(xt)[0]) > 1:
    for i in range(len(x)):
      xt[i] = act(xt[i]-(e*sum_j(x,i)))
    print(xt)
  return np.nonzero(xt)[0][0], x[np.nonzero(xt)[0][0]]

In [ ]:
e1 = [1, -1, 1, -1, 1, -1]
e2 = [-1, 1, -1, 1, -1, -1]
e3 = [1, 1, 1, -1, -1, -1]

In [ ]:
V1= [1, 1, 1, 1, 1, 1]
V2 = [-1, 1, -1, -1, 1, 1]
V3 = [-1, -1, 1, 1, 1, 1]
V4 = [-1, -1, 1, 1, -1, 1]
V5 = [-1, 1, 1, -1, -1, -1]

In [ ]:
ep = 0.13

In [ ]:
es = [e1, e2, e3]

In [ ]:
def hamming_net(es, v, ep):
  xt = np.matmul(v, np.array(es).T)+(len(v)/2)
  i, vl = maxnet(xt, ep)
  print('base vec of ', v, ' is ', 'e', i, ' = ', es[i])

In [ ]:
hamming_net(es, V1, ep)

[3. 1. 3.]
[2.48 0.22 2.48]
[1.96 0.   1.96]
base vec of  [1, 1, 1, 1, 1, 1]  is  e 0  =  [1, -1, 1, -1, 1, -1]


In [ ]:
hamming_net(es, V2, ep)

[1. 3. 1.]
[0.48 2.74 0.48]
[0.   2.48 0.  ]
base vec of  [-1, 1, -1, -1, 1, 1]  is  e 1  =  [-1, 1, -1, 1, -1, -1]


In [ ]:
hamming_net(es, V3, ep)

[ 3.  1. -1.]
[3.   0.74 0.  ]
[3.   0.48 0.  ]
[3.   0.22 0.  ]
[3. 0. 0.]
base vec of  [-1, -1, 1, 1, 1, 1]  is  e 0  =  [1, -1, 1, -1, 1, -1]


In [ ]:
hamming_net(es, V4, ep)

[1. 3. 1.]
[0.48 2.74 0.48]
[0.   2.48 0.  ]
base vec of  [-1, -1, 1, 1, -1, 1]  is  e 1  =  [-1, 1, -1, 1, -1, -1]


In [ ]:
hamming_net(es, V5, ep)

[3. 5. 7.]
[1.44 3.7  5.96]
[0.   2.4  4.92]
[0.   1.1  3.88]
[0.   0.   2.84]
base vec of  [-1, 1, 1, -1, -1, -1]  is  e 2  =  [1, 1, 1, -1, -1, -1]
